version: '3.9'
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/bookrec
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookrec
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  worker:
    build: .
    command: rq worker book-encoding
    depends_on:
      - web
      - redis
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/bookrec
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
  windsurf:
    image: windsurf/frontend:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://web:8000
volumes:
  pgdata:
